export enum ERROR {
  REQUIER_MSG = "EL CAMPO ES OBLIGATORIO",
  PASSWORD_NOT_MATCH = "LAS CONTRASEÑAS DBEN SER IGULES",
  USER_EXIST = 'EL USUARIO YA EXISTE',
  INCORRECT_LOGIN_PARAMS = 'EL USUARIO Y/O CONTRASEÑA SON INCORECTOS',
  SOMETHING_WENTH_RONG = "PARECE QUE ALGO SALIO MAL",
}
